### ISSUE TITLE
The location shown on homepage is not adding any value. We are just telling the user where they live!! 

### ISSUE THREAD

**Issue by kamalme** [kamalme/Nuptistapp#88]
I suggest that the country is fixed to INDIA. It should be a dropdown of the countries of the world.

IF we want to capture where the user is logging from, then capture it in another place, but not on the homepage. 
<img width="433" alt="image" src="https://user-images.githubusercontent.com/38006950/217167693-b364da98-6a9f-44fd-9032-da8a35ed2e3e.png">

**Comment by amankhare26** [comment]
Done
