### ISSUE TITLE
Offer/add-on addition button is a nightmare.

### ISSUE THREAD

**Issue by kamalme** [kamalme/Nuptistapp#91]
That button has many functions
1. See details of the service/product
2. Add or remove that offer
3. See vendors under that offer.

We need to give proper clarity here.

Here is the simple solution.
There should be only two options there:- 
1. add/remove(already there). This button should change to select a user.
2. See detail. Make the link of the text for seeing detail.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/38006950/217194132-488fc715-be74-45d8-8d0a-09dc1ecdd515.png">

**Comment by amankhare26** [comment]
Done
